# Generated by Django 5.0.6 on 2024-11-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0021_remove_jobmodel_skills_required_jobmodel_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofilemodel",
            name="company_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplymodel",
            name="Apply_Image",
            field=models.ImageField(null=True, upload_to="Media/Apply_Image"),
        ),
    ]
